# Generated by Django 4.1 on 2023-03-04 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0005_subcategory_categorys'),
        ('seller', '0002_alter_product_latitude_alter_product_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='item',
        ),
        migrations.AddField(
            model_name='product',
            name='item',
            field=models.ManyToManyField(related_name='category', to='buyer.subcategory'),
        ),
    ]
