# Generated by Django 4.1 on 2023-03-04 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0006_remove_subcategory_categorys'),
        ('seller', '0003_remove_product_item_product_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='item',
        ),
        migrations.AddField(
            model_name='product',
            name='item',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subcategory', to='buyer.subcategory'),
        ),
    ]
