# Generated by Django 4.1 on 2023-03-04 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='image',
            new_name='categoryId',
        ),
    ]
