# Generated by Django 4.1 on 2023-03-04 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0002_rename_image_category_categoryid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='categoryId',
            new_name='image',
        ),
    ]
