# Generated by Django 4.1 on 2023-03-04 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0003_rename_categoryid_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='fcategory',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='images/'),
        ),
    ]
