# Generated by Django 4.1 on 2023-03-04 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0004_fcategory_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='categorys',
            field=models.ManyToManyField(related_name='category', to='buyer.category'),
        ),
    ]
