# Generated by Django 4.1 on 2023-03-04 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0005_subcategory_categorys'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='categorys',
        ),
    ]
